spring:
  mvc:
    log-request-details: true # ?? ???? ?? ?? (?? ??????? ??? ???)
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db?useSSL=false
    username: user
    password: topsecret!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: ERROR
